baseurl: /down
markdown: rdiscount
pygments: true
permalink: /posts/:year/:month/:day/:title
rdiscount:
  extensions: [smart]
title : Fueled By Soda
production_url : http://fueledbysoda.github.com
description : "Fueled By Soda"
copyright :
  holder : Fueled By Soda, Inc
  year : 2013
#disqus_shortname: caarlos0blog
#analytics: UA-32899481-1
#gauges: 50f2b533613f5d7c8000000c
author :
  name : Kartik Patel
  github : fueledbysoda
  twitter : fueledbysoda
